import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sessionwrapper from "@/components/SessionWrapper";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Sessionwrapper>
          <Navbar />
          <div className="[background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)] text-white min-h-[83vh]">
          {children}
          <ToastContainer theme="dark" autoClose={4000}/>
          </div>
          <Footer />
        </Sessionwrapper>
      </body>
    </html>
  );
}